---
title: "Instart Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
   orientation: row
   runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(shiny)
```


```{r read_p1,message=FALSE}
instacart = read_csv("./data/instacart_train_data.csv.zip")
```




Column {.sidebar}
-----------------------------------------------------------------------
```{r sidebar}
department = instacart %>% distinct(department) %>% pull()

# selectInput widget
selectInput("department_choice",label = h3("Select Department"),choices = department)

max_num = (instacart %>% group_by(department, aisle) %>% count())$n %>% max()
  
# sliderInput widget
sliderInput("number_range",label = h3("Choose the number ranges"),min = 500, max = max_num,value = c(1000,300000))

```



Row
-----------------------------------------------------------------------
### Number of orders in one department
```{r bar,message=FALSE}
renderPlotly({
instacart %>% 
  count(department, aisle, aisle_id) %>%
  filter(department == input$department_choice,
         n %in% input$number_range[1]:input$number_range[2]) %>%
  mutate(order_count = n,
         aisle = factor(aisle),
         aisle = fct_reorder(aisle, n),
         text_label = str_c("aisle id:", aisle_id, "\nDepartment: ", department)) %>%
  plot_ly(x = ~ aisle, y = ~ order_count, color = ~ aisle, type = "bar", text = ~text_label)
})

```




Row {.tabset .tabset-fade}
-----------------------------------------------------------------------
### Heatmap for number of orders in each day of week by departments
```{r}
renderPlotly({
instacart %>% 
  filter(department == input$department_choice) %>%
  mutate(order_dow = factor(order_dow),
         order_dow = fct_recode(order_dow,
                                "Monday" = "0",
                                "Tuesday" = "1",
                                "Wednesday" = "2",
                                "Thursday" = "3",
                                "Friday" = "4",
                                "Saturday" = "5",
                                "Sunday" = "6")) %>%     #recode the order_dow
  group_by(order_dow, department, aisle, aisle_id) %>% 
  count() %>% 
  mutate(order_count = n,
         text_label = str_c("aisle id:", aisle_id, "\nDepartment: ", department)) %>%
  plot_ly(x = ~aisle, y = ~order_dow, z = ~order_count, type = "heatmap", text = ~text_label)
})
```

###Distribution of order hour of day by aisles in one department
```{r Distri}
renderPlotly({
distr_order_hour = 
  instacart %>% 
  group_by(department, aisle, aisle_id, order_hour_of_day) %>%
  count() %>%
  filter(department == input$department_choice) %>%
  mutate(order_count = n) %>%
  ggplot(aes(x = order_hour_of_day, y = order_count, color = aisle)) +
  geom_point() +
  geom_line()

ggplotly(distr_order_hour)
})
```




